import "./globals.css";
import Providers from "@/components/Providers/Providers";

export const metadata = {
  title: "AI Tools",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" data-theme="light">
      <body>
        <Providers>
          <main className="min-h-screen w-[90%] mx-auto py-5">{children}</main>
        </Providers>
      </body>
    </html>
  );
}
